### ISSUE TITLE
ZendeskSupport.initialize is not a function

### ISSUE THREAD

**Issue by llaine** [synapsestudios/react-native-zendesk-support#11]
Just trying to import the module doesn't work.
```typescript
const ZendeskSupport = require('@synapsestudios/react-native-zendesk-support');

componentWillMount() {
      ZendeskSupport.initialize({ ... }) // throw ZendeskSupport.initialize is not a function
}
```

Trying to `console.log` the ZendeskSupport object gives me an empty object. 

Any ideas?

**Comment by austinthetaco** [comment]
Hi @llaine , Have you already installed and linked the necessary files?

**Comment by llaine** [comment]
Yes I did. @austinthetaco but seems as if it doesn't exists.
Also had to change the Podfile to : 

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
  end
end
```

Otherwise I wasn't able to compile.

**Comment by pietro909** [comment]
@llaine did you solve it?
I had the same problem when moving from the old `react-native-zendesk-support` to `@synapsestudios/react-native-zendesk-support` and it turned out that I had to:

1. re-link the library
2. add again the library from `node_modules/@synapsestudios/react-native-zendesk-support/ios/` to the XCode project
3. manually update the `import Zendesk from "@synapsestudios/react-native-zendesk-support"` because Flow wasn't catching it

Please let me know if you still have problems.

**Comment by llaine** [comment]
@pietro909 Yes but no, I ended up using a different solution that doesn't rely on this package.

**Comment by YogeshYo** [comment]
@llaine, can you please suggest the solution you followed as I am also stuck on this? Thanks

**Comment by llaine** [comment]
@YogeshYo I ended up bridging the native IOS module of Zendesk. In my case I just needed to display the help center, which was one native call to bridge.

**Comment by YogeshYo** [comment]
@llaine, Thank You for your reply. My requirement is also same. so i am trying native module but getting undefined error..  nom install --save react-native-zendesk-sdk.. Can you share the link of your native module please

**Comment by pietro909** [comment]
@YogeshYo have you tried my solution by any chance?

**Comment by YogeshYo** [comment]
@pietro909, Ya I tried  but no luck

**Comment by YogeshYo** [comment]
@pietro909, can you please help me by clarifying 
"manually update the import Zendesk from "@synapsestudios/react-native-zendesk-support" because Flow wasn't catching it"

**Comment by pietro909** [comment]
If you use Flow, you need to replace

`import Zendesk from "react-native-zendesk-support"`

with

`import Zendesk from "@synapsestudios/react-native-zendesk-support"`

**Comment by YogeshYo** [comment]
@pietro909, I will try again & get back to you. Thanks

**Comment by YogeshYo** [comment]
@pietro909 tried but getting same error

**Comment by llaine** [comment]
@YogeshYo If you want to bridge the native IOS zendesk module in Objective-c, follow this article https://facebook.github.io/react-native/docs/native-modules-ios, install properly the zendesk IOS module and add this function to display the help center.

```objective-c

RCT_EXPORT_METHOD(showHelpCenter) {
  dispatch_async(dispatch_get_main_queue(), ^{

    [ZDKTheme currentTheme].primaryColor = [UIColor orangeColor];
    AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    UIViewController *helpCenter = [ZDKHelpCenterUi buildHelpCenterOverviewUiWithConfigs:@[]];
    UINavigationController *nav = [UINavigationController new];
    nav.modalPresentationStyle = UIModalPresentationPopover;
    [nav pushViewController:helpCenter animated:true];
    [delegate.window.rootViewController presentViewController:nav animated:true completion: nil];
  });
}
```

**Comment by YogeshYo** [comment]
@llaine, Thank you for your help. I have pushed Native Module here https://www.npmjs.com/package/react-native-zendesk-sdk
with mentioned steps (able to call TestMethod) but trap on this after Zendesk integration
"error: unknown receiver 'ZDKConfig'; did you mean 'ZDKCoding'?" although it is linked properly (checked Header)

Note: Used manual way where used frameworks from "5.0" folder (https://github.com/zendesk/zendesk_sdk_ios)

**Comment by YogeshYo** [comment]
@llaine, can you please take a look on this https://www.npmjs.com/package/react-native-zendesk-sdk (ios)

**Comment by llaine** [comment]
I'd need to look at the code, to tell you exactly what's wrong.

But basically once your bridge is done, you just need to connect it to an action or a `onClick` fn from a `<Button>`, etc.

**Comment by YogeshYo** [comment]
@llaine, i am able to call testMethod but unable to compile says "Unknown receiver 'ZDKConfig'; did you mean 'ZDKCoding'?"

**Comment by YogeshYo** [comment]
@llaine, did you got the chance to look into this?
