### ISSUE TITLE
Unable to find module with Gradle path ':@synapsestudios/react-native-zendesk-support' (needed by module 'app'.)

### ISSUE THREAD

**Issue by laxmikantprajapatigate6** [synapsestudios/react-native-zendesk-support#12]
Unable to find module with Gradle path ':@synapsestudios/react-native-zendesk-support' (needed by module 'app'.)

**Comment by bobeagan** [comment]
https://github.com/synapsestudios/react-native-zendesk-support#manually-linking-android
