### ISSUE TITLE
Light color icons for android

### ISSUE THREAD

**Issue by ravirupareliya** [synapsestudios/react-native-zendesk-support#26]
There is feedback icons at the bottom of each complain/instruction, but it is showing light color in android while in iOS it is working perfect. Here is the reference screenshots.

![Screenshot_1554465280](https://user-images.githubusercontent.com/17959204/55625977-edb9dc80-57c7-11e9-92a1-868965527f65.png)![Simulator Screen Shot - iPhone X - 2019-04-05 at 17 24 27](https://user-images.githubusercontent.com/17959204/55625978-edb9dc80-57c7-11e9-8a4d-1dcae1f18a65.png)

**Comment by caseyt** [comment]
Please see the "Styling Category Headers" section of the README which describes how to load a custom android theme for your Zendesk implementation:

```
<resources>
    <style name="AppTheme" parent="ZendeskSdkTheme.Light">
      <item name="colorPrimary">#FF6240</item>
    </style>
</resources>
```

And also this Zendesk Android SDK document that describes the available custom values: https://developer.zendesk.com/embeddables/docs/android/customize_the_look#use-your-own-theme
