### ISSUE TITLE
TypeError: _reactNativeZendeskSupport.default.initialize is not a function

### ISSUE THREAD

**Issue by YogeshYo** [synapsestudios/react-native-zendesk-support#29]
**What I did:**
1. npm install --save @synapsestudios/react-native-zendesk-support 
2. npm link @synapsestudios/react-native-zendesk-support 
3. iOS pod install 
rechecked Manually Linking (iOS) & found they were in place.

still getting this error
TypeError: _reactNativeZendeskSupport.default.initialize is not a function
TypeError: _reactNativeZendeskSupport.default.setupIdentity is not a function

**Comment by JeffreyLeeDave** [comment]
is there a reason this was closed? i see that this might be fixed in 1.0.3, but there hasn't been any update on that for almost a month right?

**Comment by bobeagan** [comment]
Closed by the user, guessing it was something they were doing incorrectly.
