### ISSUE TITLE
Create tickets in the background without zendesk's UI.

### ISSUE THREAD

**Issue by nabylb** [synapsestudios/react-native-zendesk-support#31]
The Zendesk SDK has an API providers that can create and query tickets in the background without invoking the UI. There needs to be a React Native implementation of the [createRequest](https://developer.zendesk.com/embeddables/docs/ios/requests#createrequest) method that calls a request service to create a request on behalf of the end user.

**Comment by nabylb** [comment]
I have a PR ready for review to add this feature.

**Comment by bobeagan** [comment]
We'll try to get someone to review it this week so we can get it merged into the next release for this project. Thanks for contributing!

**Comment by nabylb** [comment]
@bobeagan, any update on the review?
