### ISSUE TITLE
Undefined symbols for architecture x86_64: Xcode 9.4.1, RN 0.55.4

### ISSUE THREAD

**Issue by hariks789** [synapsestudios/react-native-zendesk-support#7]
I tried adding ZenDesk to my Project but build is failing,
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ZDKAnonymousIdentity", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
  "_OBJC_CLASS_$_ZDKConfig", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
  "_OBJC_CLASS_$_ZDKCustomField", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
  "_OBJC_CLASS_$_ZDKHelpCenter", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
  "_OBJC_CLASS_$_ZDKHelpCenterOverviewContentModel", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
  "_OBJC_CLASS_$_ZDKRequests", referenced from:
      objc-class-ref in libRNZenDeskSupport.a(RNZenDeskSupport.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Steps I followed
1. npm install react-native-zendesk-support 1.0.9
2. react-native link react-native-zendesk-support
3. Manually added SDK from official repo, tried both v1 and v2

React-Native 0.55.4
Node 8.11.3
NPM 5.6.0
Xcode 9.4.1
Swift 4.1.2
Mac OS High Sierra

Please let me know if I am doing it wrong. Any help would be greatly appreciated
Thanks

**Comment by elirangoshen** [comment]
the same.. how you solve it ?

**Comment by scaralfred** [comment]
How did you solve it? Same boat...

**Comment by bintoll** [comment]
+ 1 also have this, did not found any solution, unfortynately

**Comment by hariks789** [comment]
Sorry for the late reply. I ended up with building my own wrapper with the help of codes from this repo and similar ones. I couldn’t make v2 sdk work on android So ended up with v2 for iOS and v1 for android

**Comment by YogeshYo** [comment]
@hariks789, can you please share those wrappers?
